interview_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
	# path("", include("login_page.urls")),
	# path("login_page/", include("login_page.urls")),
	path("admin/", admin.site.urls),
	url("questions/", include("questions.urls")),
    url("",           include("login_page.urls")),
    # url("create_post",include("login_page.urls")),
]

questions/urls.py
from django.urls import path
from . import views
app_name = "questions"
urlpatterns = [
    # ex: /questions/
    # path('', views.index, name='index'),
    # path("index", views.auth, name='auth'),
    # path("next_quest", views.next_quest, name='next_quest'),
    path("create_post", views.create_post, name='create_post'),
    path("thank_you", views.thank_you, name='thank_you'),
]

questions/models.py
from django.db import models

# Create your models here.

questions/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.http.response import HttpResponse
from login_page.models import Q_A, multiple_choices, interview_info
import random
from django.contrib.auth.decorators import login_required
import pytz


lst = []
q_id_to_skip = []
dificulty_level_ = 1
score = 0
quiestion_number = 1
correct_answers_qty = 0
max_dificulty_level = list(Q_A.objects.raw("SELECT *, max(dificulty_level) FROM Q_A;"))[0].dificulty_level

# def index(request):
#     return HttpResponse("<h1>Login page</h1>")

# def index(request):
# 	print(".............. questions.index called")
# 	return render(request, 'questions/q_page.html', {"name" : "Amir"})

# def auth(request):
# 	print(".............. questions.auth called")
# 	auth_result = authenticaion(request)
# 	if auth_result:
# 		next_quest(request)

# def tr(request):
# 	return HttpResponse("<h1>TR</h1>")


def get_multiple_choices(q_id):	
	print(".............. questions.get_multiple_choices called")
	raw_query = f"SELECT * FROM multiple_choices WHERE Q_id = '{q_id}'"
	x = list(multiple_choices.objects.raw(raw_query))
	options = [i.option for i in x]
	return options

def next_quest_2(selected_option, q_id):
	global dificulty_level_
	global score
	global quiestion_number
	global correct_answers_qty
	import datetime as dt_
	# lst.append([q_id, selected_option, dt_.datetime.now(), dificulty_level_])
	lst.append([q_id, selected_option, dt_.datetime.now(pytz.timezone('Asia/Karachi')), dificulty_level_])

	q_id_to_skip.append(q_id)

	x = Q_A.objects.raw(f"select * from Q_A where id = '{q_id}'")
	id_, Q, A, dificulty_level = [(i.id, i.Q, i.A, i.dificulty_level) for i in x][0]
	quiestion_number += 1
	# print(f"q_id: {q_id}\nid_: {id_}\nQ: {Q}\nA: {A}\ndificulty_level: {dificulty_level}")
	if A == selected_option:
		correct_answers_qty += 1
		score += dificulty_level_
		if dificulty_level_ < max_dificulty_level:
			dificulty_level_ += 1
	else:
		if dificulty_level_ > 1:
			dificulty_level_ -= 1 
	lst[-1].append(score)
	while True:
		raw_query = f"select * from Q_A WHERE dificulty_level = '{dificulty_level_}' AND id NOT IN {str(tuple(q_id_to_skip)).replace(',)', ')')};"
		x = list(Q_A.objects.raw(raw_query))
		random.shuffle(x)
		if len(x) > 0:
			q_id, question, answer, dificulty_level =  x[0].id, x[0].Q, x[0].A, x[0].dificulty_level
			break
		else:
			return "Questions ended in DB"

	params_ = {
			"score" : score,
			"quiestion_number" : quiestion_number,
			'Question' : question, 
			"answer" : answer,
			"q_id" : q_id,
			"dificulty_level" : dificulty_level,
			"correct_answers_qty" : correct_answers_qty,
			"L" : get_multiple_choices(q_id)
			}
	return params_


@login_required
def thank_you(request):
	user_name = request.user
	from django.contrib.auth import logout
	logout(request)
	log_interview(request, quiestion_number, correct_answers_qty, score, lst, 'loged out', user_name=user_name)
	return render(request, 'questions/thank_you.html')

def next_quest(request):
	print(".............. questions.next_quest called")
	try:
		selected_option = request.POST["selected_option"]
		q_id = request.POST["custId"]
	except:
		return HttpResponse("<h1>No option selected</h1>")
	
	params_ = next_quest_2(selected_option, q_id)
	if params_ == "ERROR":
		return render(request, 'questions/thank_you.html')
	return render(request, 'questions/q_page.html', params_)
	# else:
		# return HttpResponse("<h1>Incorrect email or password</h1>")

@login_required
def create_post(request):
	print("#################################### 1")
	print("\n.............. questions.create_post called")
	global dificulty_level_
	global score
	global quiestion_number
	global correct_answers_qty
	import json
	if request.is_ajax():
		print("#################################### 2")
		try:
			if str(request.POST['time_out']) == "true":
				params_ = 'Time out'
		except:
			selected_option = request.POST["selected_option"]
			q_id = request.POST["q_id"] #custId
			params_ = next_quest_2(selected_option, q_id)

		if isinstance(params_, dict):
			print("#################################### 3")
			params_['sucess'] = "True"
		else:
			if params_ == "Questions ended in DB":
				print("#################################### 4")
				log_interview(request, quiestion_number, correct_answers_qty, score, lst, 'Questions ended in DB')
				params_ = {"sucess" : "False"}
				# interview khatam hony par ye log karna h, magar interview khatam hony ka ye 1 synario h (k questions ki qty baqi ho magar ksi bhi 1 dificulty level k sary question ho gay hon)
				# user khud logout kar day      ?????????? is ki impelementation baqi h
			elif (quiestion_number > 20):
				print("#################################### 5")
				log_interview(request, quiestion_number, correct_answers_qty, score, lst, 'Questions ended')
				params_ = {"sucess" : "False"}
			elif params_ == 'Time out':
				log_interview(request, quiestion_number, correct_answers_qty, score, lst, 'Time out')
				params_ = {"sucess" : "False"}
			# return HttpResponse("<h1>No question left</h1>")\
			# redirect("http://127.0.0.1:8000/accounts/login/")
			# return JsonResponse({})
			# return HttpResponse(json.dumps({"nothing to see": "this isn't happening"}),content_type="application/json")
			# return render(request, template_name="No_question_left.html")
		# print (json.dumps(params_, indent=2, default=str))
		# {'score': 0, 'quiestion_number': 7, 'Question': 'Question 11', 'answer': 'Answer 11', 'q_id': 11, 'dificulty_level': 1, 'correct_answers_qty': 0, 'L': ['Answer 11', 'b', 'p', 'x']}
		# return HttpResponse(json.dumps(params_),content_type="application/json")
		# print(params_)
		print("#################################### 6")
		return JsonResponse(params_)
		# return redirect('account') # path('account/', views.userAccount, name="account"),

		# return HttpResponse("<h1>No option selected</h1>")

		# if selected_option and q_id: #cheking if first_name and last_name have value
		# 	response = {'msg':'Your form has been submitted successfully'} # response message}
		# 	return JsonResponse(response) # return response as JSON




def log_interview(request, quiestion_number, correct_answers_qty, score, lst, ending_reason, user_name=None):
	from login_page.models import Q_A, multiple_choices, interview_logs, interview_info
	import datetime
	from django.contrib.auth.models import User 
	if user_name is None:
		user_id = User.objects.get(username=request.user).id 
	else:
		user_id = User.objects.get(username=user_name   ).id
	total_questions = 20 # hard coded, should be replaced
	
	start_time = open("start_time.txt", 'r').read().strip()
	start_time = datetime.datetime.fromisoformat(start_time)

	# end_time = datetime.datetime.now()
	end_time = datetime.datetime.now(pytz.timezone('Asia/Karachi'))
	time_spent_in_minutes = (end_time - start_time).total_seconds() // 60

	incorrect_answers_qty = quiestion_number - correct_answers_qty

	interview_info.objects.create(
		user_id = user_id,
		start_time = str(start_time),
		time_spent_in_minutes = time_spent_in_minutes,
		correct_answers_qty = correct_answers_qty,
		incorrect_answers_qty = incorrect_answers_qty,
		total_questions = total_questions,
		time_provided_in_minutes = 20,
		score = score,
		is_completed_all_questions = (1 if (correct_answers_qty + incorrect_answers_qty) == total_questions else 0),
		ending_reason = ending_reason
		).save()

	from django.core.mail import send_mail
	from interview_app.settings import EMAIL_HOST_USER
	subject = "Subject"
	message = "Message"
	if user_name is None:
		recepient = User.objects.get(username=request.user).email
	else:
		recepient = User.objects.get(username=user_name   ).email
	send_mail(subject, message, EMAIL_HOST_USER, [recepient], fail_silently = False)

	for e, i in enumerate(lst):
		Q_id, selected_option, time_, dificulty_level_, score = i
		Q_id = int(Q_id)
		q = Q_A.objects.get(id=Q_id)
		Q = q.Q
		A = q.A

		interview_logs.objects.create(
			# interview_id = interview_info.objects.get(user_id=user_id).id,
			interview_id = interview_info.objects.filter(user_id=user_id).last().id,
			user_id = user_id,
			Question_number = e,
			Q_id = Q_id,
			time = time_,
			Question = Q,
			dificulty_level = dificulty_level_,
			Selected_option = selected_option,
			is_correct = (A == selected_option),
			Options = '|  ' + '\n|  '.join([f"{e}- {i.option}" for e,i in enumerate(multiple_choices.objects.filter(Q_id=Q_id), 1)]),
			Correct_answer = A,
			score = score
			).save()

questions/templates/questions/q_page.html
{% load static %}
<html>
    <head>
        <title>LFD online MCQ</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    </head>
	<body>
		<center>
			<h3>
				<p id="demo"></p>
			</h3>
		</center>
<!-- 		<script>
			// Set the date we're counting down to
			// var countDownDate = new Date("Jul 18, 2021 18:55:00").getTime();
			var total_interview_minutes = 20; 
			var distance = total_interview_minutes * 60;
			// Update the count down every 1 second
			var x = setInterval(function() {
				// Get today's date and time
				// var now = new Date().getTime();

				// Find the distance between now and the count down date
				// var distance = countDownDate - now;

				// Time calculations for days, hours, minutes and seconds
				// var days = Math.floor(distance / (1000 * 60 * 60 * 24));
				distance = distance - 1 ;
				var hours = Math.floor((distance % (60 * 60 * 24)) / (60 * 60));
				var minutes = Math.floor((distance % (60 * 60)) / 60);
				var seconds = Math.floor((distance % 60));
				// Output the result in an element with id="demo"
				// document.getElementById("demo").innerHTML = days + "d " + hours + "h " + minutes + "m " + seconds + "s ";
				// document.getElementById("demo").innerHTML = distance;
				document.getElementById("demo").innerHTML = hours + "h " + minutes + "m " + seconds + "s ";
				// If the count down is over, write some text 
				if (distance < 0) {
					clearInterval(x);
					// document.getElementById("demo").innerHTML = "EXPIRED";
					// time khatam hony par is link par redirect kar do
					location.replace("http://127.0.0.1:8000/accounts/logout/")
					// yahan par user ka sara data DB me dump karna h
					}
				}, 1000);
		</script> -->
		<script type="text/javascript">
				var total_interview_minutes = 20; 
				var distance = total_interview_minutes * 60;
				var x = setInterval(function() {
					distance = distance - 1 ;
					var hours = Math.floor((distance % (60 * 60 * 24)) / (60 * 60));
					var minutes = Math.floor((distance % (60 * 60)) / 60);
					var seconds = Math.floor((distance % 60));
					document.getElementById("demo").innerHTML = hours + "h " + minutes + "m " + seconds + "s ";
					if (distance == 0) {
						clearInterval(x);


						// ----------------------------------------
						// agar time out out ho jay to interview_info table k <ending_reason> column me <Time out> push karna h
						$.ajax({
							type : "POST",
							url : "{% url 'questions:create_post' %}",
						    data : {
								csrfmiddlewaretoken : $('input[name=csrfmiddlewaretoken]').val(),
							    time_out : "true"
						    },
			                success: function(data){
								// var logout_url    = "http://127.0.0.1:8000/accounts/logout/";
		                		// location.replace(logout_url);

								var thank_you_url = 'http://127.0.0.1:8000/questions/thank_you';
		                		location.replace(thank_you_url);
			                },
						})

						// ----------------------------------------


					}
						}, 1000);
		</script>
		<!-- <form action="/questions/next_quest" method="post">  -->
		<!-- <form action="/create_post/" method="POST" id="my_form"> -->
		<form  method="post" id="my_form" action="">
			{% csrf_token %}
	        <div class = "display-3 color-red">
	        	<center>
	        		<h1>
	        			<div id="q_">Q: {{Question}}</div>
		        	</h1>
		        	<h5>
		        		<div id="q_id">q_id: {{q_id}}</div>
		        		<div id="answer">Correct Answer: {{answer}}</div>
		        		<div id="dificulty_level">Difficulty level: {{dificulty_level}}</div>
		        		<div id="score">Score: {{score}}</div>
		        		<div id="quiestion_number">Question #: {{quiestion_number}}</div>
		        		<div id="correct_answers_qty">Correct answers Qty.: {{correct_answers_qty}}</div><br>
					</h5>
	        	</center>
	        </div>
			<input type="hidden" id="my_custId" name="my_custId_" value={{ q_id }}>
			{% for i in L %}

				<!-- <input type="radio" id='id_{{ forloop.counter0 }}' name="selected_option"> -->
				<!-- <label id='_id_{{ forloop.counter0 }}'>{{i}}</label> -->
				<!-- opar wala galat h, us block ko use kany sy first selected_option ki value hamesha 'on' hoti h regardles of user input -->

				<input type="radio" id='id_{{ forloop.counter0 }}' name="selected_option" value="{{i}}">
				<label id='_id_{{ forloop.counter0 }}'>{{i}}</label><br>
				<!-- <label for="html">{{ i }}</label><br> -->
			{% endfor %}
			<br>
			<input type="submit" value="Submit">
		</form>
		<a href="{% url 'logout' %}">Logout</a>
      <div id="output"></div>
		<!-- {% block javascript %} -->
		<script type="text/javascript"> 
            $('#my_form').submit(function (e) {
			    e.preventDefault();
            	// <input type="hidden" id="my_custId" name="my_custId_" value={{ q_id }}>
            	// var id_ = $('#my_custId').val();
				// var id_ = $('input#my_custId').val();
				// var id_ = $('input[name=my_custId_]').val();
				// var id_ = $('input[type=hidden]').val();
				// var id_ = $(':hidden#my_custId').val();
				// var id_ = $('input:hidden[name=my_custId_]').val();
				// var id_ = $('[name=my_custId_]');
				// var id_ = $('#my_custId').val();
				// var id_=$ ('input[type=hidden]').val();
				// var id_=$ ( this ).find( 'input:hidden' );
				// var id_ = $("[name='my_custId_']").val(); // by name
				// var id_ = 

				// $("#output").html(
					// $(this).serialize().split("&").slice(-2, -1)[0].replace("my_custId_=", "")
					// );

				var id_             = $(this).serialize().split("&").slice(-2,-1)[0].replace("my_custId_=",      "");

            	// var selected_option = $(this).serialize().split("&").slice(-1)   [0].replace("selected_option=", "").replace("%20", " ")
            	// opar wala bhi same kaam kar raha h, magar wo propar tareeqa nahi h.
            	var selected_option = $('input[name="selected_option"]:checked').val()
				// $("#output").html(selected_option);
            	// var selected_option = $("input[type='radio']:checked").val() // ye bhi sahi h

            	// $('#output').html(selected_option)

            	// alert (id_ + ' ' + selected_option)
            	// var url  = "/questions/next_quest";
        	    var div_0=document.getElementById("id_0").value;
        	    var div_1=document.getElementById("id_1").value;
        	    var div_2=document.getElementById("id_2").value;
        	    var div_3=document.getElementById("id_3").value;
        	    // alert (div_0 + ' ' + div_1 + ' ' + div_2 + ' ' + div_3)
				$.ajax({
					type : "POST",
					url : "{% url 'questions:create_post' %}",
					// !!!!!!!!!!!!! ye url ka 1 function bana hona chahye or us function ko us link par <urls.py> file me connect hona chahye.
					// url : "/likepost",
					// urlpatterns wala name aay ga. eg: <contact_submit> for  <path('ajax/contact', app1.postContact, name ='contact_submit')>
					// url : '127.0.0.1:8000/hello',
					// url : {% url 'dashboard'  %}, // view.dashboard
				    data : {
						csrfmiddlewaretoken : $('input[name=csrfmiddlewaretoken]').val(),
					    q_id : id_,
					    selected_option : selected_option
				    },
	                success: function(data){
	                	if (data.sucess == "False"){
	                		var thank_you_url = 'http://127.0.0.1:8000/questions/thank_you';
	                		location.replace(thank_you_url);
	                	}
    	                $("input[id=id_0]").val(data.L[0]);
    	                $("input[id=id_1]").val(data.L[1]);
    	                $("input[id=id_2]").val(data.L[2]);
    	                $("input[id=id_3]").val(data.L[3]);

    	                $('#_id_0').html(data.L[0]);
    	                $('#_id_1').html(data.L[1]);
    	                $('#_id_2').html(data.L[2]);
    	                $('#_id_3').html(data.L[3]);

    	                $('#q_').html('Q: ' + data.Question); 
    	                $("#my_custId").attr("value",data.q_id);
    	                $('#q_id').html('q_id: ' + data.q_id);
						$('#answer').html('Correct Answer: ' + data.answer);
						$('#dificulty_level').html('Difficulty level: ' + data.dificulty_level);
						$('#score').html('Score: ' + data.score);
						$('#quiestion_number').html('Question #: ' + data.quiestion_number);
						$('#correct_answers_qty').html('Correct answers Qty.: ' + data.correct_answers_qty);

	                	// location.reload(false);
	                	// var q=data.L[0]
	                	// $('id_0') = q
	            	    // $('#id_0').html(div_0);
    		            // $("#id_0").load(window.location + " #id_0");
    		            // $("#id_0").remove();
	                	// $.post('http://example.com/form.php', {category:'client', type:'premium'});
	                },
				})
        	});
        </script>
        <!-- {% endblock javascript %} -->
	</body>
</html>

questions/templates/questions/q_page_OK.html
{% load static %}
<body bgcolor='RoyalBlue'>
	<h1>
		Question: {{Question}}
		<h4>
			q_id : {{q_id}}<br>
			Actual answer: {{answer}}<br>
			Dificulty level: {{dificulty_level}}<br>
			score : {{score}} <br>
			quiestion_number : {{quiestion_number}}<br>
			correct_answers_qty : {{correct_answers_qty}}<br>
		</h4>
		<br><br>
		<form action="/questions/next_quest" method="post">
			{% csrf_token %}
			<input type="hidden" id="custId" name="custId" value={{ q_id }}>
			{% for i in L %}
				<input type="radio" id={{ i }} name="selected_option" value="{{i}}">
				<label for="html">{{ i }}</label><br>
			{% endfor %}
			<br>
			<input type="submit" value="Submit">
		</form>
	<h1>
</body>

questions/templates/questions/thank_you.html
<!DOCTYPE html>
<html>
<head>
<style>
.center {
  line-height: 200px;
  height: 200px;
  border: 3px solid green;
  text-align: center;
}
</style>
</head>
<body>

<div class="center">
	<p>
  		<h1>
  			Thank you for participating.
  		</h1>
	</p>
</div>

</body>
</html>